query Home {
  home {
    seo {
      title
      description
    }
    hero {
      title
      subtitle
      button {
        label
        path
      }
      image {
       url
      }
    }
  }
}